- hosts: all
  vars:
    docker_dir: /opt/docker
  tasks:
    - name: stat /usr/bin/docker
      stat:
        path: /usr/bin/docker
      register: reg_docker

    - name: get docker
      uri:
        url: https://get.docker.com/
        return_content: yes
      register: reg_get_docker
      when: not reg_docker.stat.exists

    - name: install docker
      shell: "{{ reg_get_docker.content}}"
      register: installDocker
      when: not reg_docker.stat.exists
      become: yes

    - name: add docker group to user
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      become: yes

    - name: Create docker directory.
      file:
        path: "{{ docker_dir }}"
        state: directory
        mode: 0775
        group: docker
      become: yes